### ISSUE TITLE
Add style format configuration file for this project

### ISSUE THREAD

**Issue by iteemhe** [jamesjuett/lobster#294]
Can we have a standardized format configuration file for Prettier <https://prettier.io/>, a formatter for TS? It also has a VS Code extension. Besides, we can include it in this project by `npm install --save-dev prettier`.

I believe standardizing the format for this repo can help us make the source code more consistent, readable and maintainable. Also it can help future maintenance and development.

Here is my `.prettierrc.toml`, we can create one for this repo. <https://prettier.io/docs/en/configuration.html> is the official doc for configuration file.

```toml
printWidth = 80
tabWidth = 4
useTabs = false
semi = true
singleQuote = false
trailingComma = "es5"
```
